FUNCTION ZLMMI002_GASSUP_SCHAGR.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(SA_NUMBER) TYPE  EBELN
*"     VALUE(DOC_TYPE) TYPE  BSART
*"     VALUE(START_DATE) TYPE  KDATB
*"     VALUE(END_DATE) TYPE  KDATE
*"     VALUE(OFFER_PARTYID) TYPE  EIKTO
*"     VALUE(UOM) TYPE  MEINS
*"     VALUE(DEST) TYPE  CHAR20 OPTIONAL
*"     VALUE(DAILY_QUANTITY) TYPE  KTMNG
*"     VALUE(COMP_CODE) TYPE  BUKRS
*"     VALUE(DELE_FLAG) TYPE  LOEKZ
*"     VALUE(PLANT) TYPE  WERKS
*"     VALUE(ZZTRLOC1) TYPE  ZTRLOCID
*"     VALUE(ZZTRLOC2) TYPE  ZTRLOCID
*"     VALUE(ZZTRLOC3) TYPE  ZTRLOCID
*"     VALUE(ZZTRLOC4) TYPE  ZTRLOCID
*"     VALUE(ZZPARTY) TYPE  ZPARTY
*"  EXPORTING
*"     VALUE(RETURNCODE) TYPE  INT4
*"----------------------------------------------------------------------
  CALL FUNCTION 'ZLMMI002_GASSUP_SCHAGR' DESTINATION DEST
    EXPORTING
      SA_NUMBER      = SA_NUMBER
      DOC_TYPE       = DOC_TYPE
      START_DATE     = START_DATE
      END_DATE       = END_DATE
      OFFER_PARTYID  = OFFER_PARTYID
      UOM            = UOM
      DAILY_QUANTITY = DAILY_QUANTITY
      COMP_CODE      = COMP_CODE
      DELE_FLAG      = DELE_FLAG
      PLANT          = DELE_FLAG
      ZZTRLOC1       = ZZTRLOC1
      ZZTRLOC2       = ZZTRLOC2
      ZZTRLOC3       = ZZTRLOC3
      ZZTRLOC4       = ZZTRLOC4
      ZZPARTY        = ZZPARTY
    IMPORTING
      RETURNCODE     = RETURNCODE.




ENDFUNCTION.
