* 2009/01/15 mdemeest TR580 - Upgrade ERP 6.0/SAPWeaver 7.00 UGL
*                             All changes marked with UGL    UGL
*                             in rightmost column            UGL
*                             includes ZLMEDRUCKF10_UGL      UGL
*                             ZLMEDRUCKF1N_UGL               UGL
*                             ZLMEDRUCKF1L_UGL               UGL
*                             ZLMEDRUCKF1K_UGL-YearEnd Msg   UGL
*                             ZLMEDRUCKF1H_UGL               UGL
*                             ZLMEDRUCKF18_UGL               UGL
*                             ZLMEDRUCKF12_UGL               UGL

  INCLUDE LMEDRUCKF1R .  " GET_PLANT_ADDRESS
  INCLUDE LMEDRUCKF1Q .  " GET_CUSTOMER_ADDRESS
  INCLUDE LMEDRUCKF1P .  " GET_VENDOR_ADDRESS

* INCLUDE LMEDRUCKF1O .  " PREPARE_FORMULAR                  UGL
* INCLUDE LMEDRUCKF1N    " PRINT_HEADER                      UGL

  INCLUDE ZLMEDRUCKF1O_UGL.  " PREPARE_FORMULAR             "UGL
  INCLUDE ZLMEDRUCKF1N_UGL .  " PRINT_HEADER                "UGL

  INCLUDE LMEDRUCKF1M .  " PRINT_APPENDIX

* INCLUDE LMEDRUCKF1L .  " PRINT_TOTAL_LINE                  UGL
* INCLUDE LMEDRUCKF1K .  " ENDE                              UGL
  INCLUDE ZLMEDRUCKF1L_UGL .  " PRINT_TOTAL_LINE            "UGL
  INCLUDE ZLMEDRUCKF1K_UGL .  " ENDE                        "UGL

  INCLUDE LMEDRUCKF1J .  " READ_HEADER_COND
  INCLUDE LMEDRUCKF1I .  " PREPARE_ITEM
  include WSTR_LMEDRUCKF1H. "Holds store groups for Purchasing
* INCLUDE LMEDRUCKF1H .  " PREPARE_ITEM_TEXT                 UGL
  INCLUDE ZLMEDRUCKF1H_UGL .  " PREPARE_ITEM_TEXT           "UGL

  INCLUDE LMEDRUCKF1G .  " PREPARE_ITEM_ADDITIONAL_DATA
  INCLUDE LMEDRUCKF1F .  " PREPARE_ITEM_COND
  INCLUDE LMEDRUCKF1E .  " VKP_ERMITTELN
  INCLUDE LMEDRUCKF1D .  " SAMMEL
  INCLUDE LMEDRUCKF1C .  " VARIANTEN
  INCLUDE LMEDRUCKF1B .  " M_AUSGEBEN
  INCLUDE LMEDRUCKF1A .  " ABWEICHUNG
  INCLUDE LMEDRUCKF19 .  " AENDERUNGEN

* INCLUDE LMEDRUCKF18 .  " PRINT_ITEM_PO                     UGL
  INCLUDE ZLMEDRUCKF18_UGL .  " PRINT_ITEM_PO               "UGL

  INCLUDE LMEDRUCKF17 .  " PRINT_ITEM_DS
  INCLUDE LMEDRUCKF16 .  " MAHNTEXT
  INCLUDE LMEDRUCKF15 .  " SET_TIMEFLAG
  INCLUDE LMEDRUCKF14 .  " TIME_INTO_PRINTFORM
  INCLUDE LMEDRUCKF13 .  " AUSGABE_COMP
* INCLUDE LMEDRUCKF12 .  " READ_HEADER_DATA                  UGL
  INCLUDE ZLMEDRUCKF12_UGL .  " READ_HEADER_DATA            "UGL

  INCLUDE LMEDRUCKF11 .  " READ_HEADER_TEXT
  INCLUDE LMEDRUCKF10 .  " MENGE_AUSGEBEN
  INCLUDE LMEDRUCKF0Z .  " FUELLEN_XAEND
  INCLUDE LMEDRUCKF0Y .  " LESEN_QM_DOCUMENTS
  INCLUDE LMEDRUCKF0X .  " PRINT_INVOICING_SCHEDULE
  INCLUDE LMEDRUCKF0W .  " AUSGABE_POS_UEB
  INCLUDE LMEDRUCKF0V .  " AUSGABE_STAMMKONDITIONEN
  INCLUDE LMEDRUCKF0U .  " LESEN_TTXIT
  INCLUDE LMEDRUCKF0T .  " PRINT_MAINTANCE_SCHEDULE
  INCLUDE LMEDRUCKF0S .  " SELECT_SERVICES
  INCLUDE LMEDRUCKF0R .  " BLOCK_TEXT_LEISTUNG
  INCLUDE LMEDRUCKF0Q .  " BLOCK_TEXT_GLIEDERUNG
  INCLUDE LMEDRUCKF0P .  " PRINT_GLIEDERUNG
  INCLUDE LMEDRUCKF0O .  " KONDITIONEN
  INCLUDE LMEDRUCKF0N .  " ZIELWERT
  INCLUDE LMEDRUCKF0M .  " PRINT_SRVPOS
  INCLUDE LMEDRUCKF0L .  " TEXTE
  INCLUDE LMEDRUCKF0K .  " PRINT_FORMEL
  INCLUDE LMEDRUCKF0J .  " PRINT_ABRUFDATEN
  INCLUDE LMEDRUCKF0I .  " PRINT_TIME
  INCLUDE LMEDRUCKF0H .  " SELECT_BLOCK_TEXT
  INCLUDE LMEDRUCKF0G .  " UMBRUCH_POSITION
  INCLUDE LMEDRUCKF0F .  " XAEND_VARIANTEN
  INCLUDE LMEDRUCKF0E .  " VARIANTEN_DATEN
  INCLUDE LMEDRUCKF0D .  " PRINT_CHANGES_SRV
