"Name: \PR:SAPLMEREQS\TY:LCL_INDEX\ME:COMPATIBILITY_CHECK\SE:BEGIN\EI
ENHANCEMENT 0 ZLMEREQSF01.
*BTBOUNDY
*P2P
  "Update the BBP State to allow changes
  CALL FUNCTION 'BBP_PO_BAPI_STATE'
    EXPORTING
      IV_SET_BAPICALL = 'X'.
ENDENHANCEMENT.
