PROGRAM ZMCDEFDE.
*=======================================================================
* Create    OSS note:28169 Repair Request:D30K904266    DS    07/23/97
*           THIS PROGRAM WILL DELETE ENTRIES FROM THE TABLE MCDEFID
*           WHERE 1) THE VALUE OF MCID IS SPACE
*                 2) THERE ARE VALUES WHICH DO NOT EXIST ANYMORE
*=======================================================================
  TABLES: MCDEFID, DD23L.
  PARAMETERS: MCOBJ LIKE DD23L-MCONAME,
              USER  LIKE SY-UNAME.
  DATA: IDD23L LIKE DD23L OCCURS 0 WITH HEADER LINE.

  SELECT * FROM DD23L INTO TABLE IDD23L
    WHERE MCONAME EQ MCOBJ AND AS4LOCAL EQ 'A'.
  SELECT * FROM MCDEFID
    WHERE SYUSER EQ USER AND MCONAME EQ MCOBJ.
    IF MCDEFID-MCID EQ SPACE.
      DELETE MCDEFID.
    ELSE.
      READ TABLE IDD23L WITH KEY MCID = MCDEFID-MCID.
      IF SY-SUBRC NE 0.
        DELETE MCDEFID.
      ENDIF.
    ENDIF.
  ENDSELECT.
