REPORT ZMINI001 MESSAGE-ID ZM NO STANDARD PAGE HEADING PAGE-COUNT 65.
************************************************************************
*  Author:   Dorothy Bialkowska
*  Brief Description:
*     - The purpose of this program is to create an extract file to
*       provide data to the STAP system.
************************************************************************

TABLES:     MARA, MAKT, MARD, T001L, T001W, T006A, T023T, T134T.

DATA:       BEGIN OF RECORD,
                  PLANT(4)         TYPE     C,
                  PLANTNME(30)     TYPE     C,
                  STORE(4)         TYPE     C,
                  STORENME(16)     TYPE     C,
                  MATNR(18)        TYPE     C,
                  QUANTITY(14)     TYPE     C,
                  UNIT(6)          TYPE     C,
                  BIN(10)          TYPE     C,
            END OF RECORD.



DATA:       MATID(18)     TYPE     C.

SELECTION-SCREEN BEGIN OF BLOCK BOX WITH FRAME TITLE TEXT-000.
   SELECTION-SCREEN SKIP 1.
   SELECT-OPTIONS     S_MATNR     FOR     MAKT-MATNR.
   SELECT-OPTIONS     S_MATTP     FOR     T134T-MTART.
   SELECT-OPTIONS     S_MATGR     FOR     T023T-MATKL.
   SELECT-OPTIONS     S_PLANT     FOR     T001W-WERKS.
   SELECT-OPTIONS     S_STORE     FOR     T001L-LGORT.
SELECTION-SCREEN END OF BLOCK BOX.

SELECTION-SCREEN BEGIN OF BLOCK BOX1 WITH FRAME TITLE TEXT-001.
   SELECTION-SCREEN SKIP 1.
   PARAMETERS:    FILE(60)
   DEFAULT '/usr/sap/interfaces/D30/outbound/MM/DRXX0104_01'
                  LOWER CASE.
SELECTION-SCREEN END OF BLOCK BOX1.

AT SELECTION-SCREEN.
   OPEN DATASET FILE FOR OUTPUT IN text MODE.
   IF SY-SUBRC NE 0.
      MESSAGE E006 WITH FILE.
   ENDIF.

TOP-OF-PAGE.
   PERFORM PRINT_TITLE.

START-OF-SELECTION.
SELECT * FROM MARD
   WHERE MATNR IN S_MATNR
   AND LVORM NE 'X'
   AND WERKS IN S_PLANT
   AND LGORT IN S_STORE.
       SELECT SINGLE * FROM MARA
          WHERE MATNR = MARD-MATNR
          AND LVORM NE 'X'.
       CHECK MARA-MTART IN S_MATTP AND MARA-MATKL IN S_MATGR.
       PERFORM GET_UNIT_OF_MEASURE.
       PERFORM GET_PLANT_NAME.
       PERFORM GET_STORAGE_NAME.
       PERFORM BUILD-RECORD.

       TRANSFER RECORD TO FILE.
       WRITE: / RECORD.
ENDSELECT.
CLOSE DATASET FILE.
************************************************************************
FORM GET_UNIT_OF_MEASURE.
     SELECT * FROM T006A
        WHERE SPRAS = SY-LANGU
        AND MSEHI = MARA-MEINS.
     ENDSELECT.
ENDFORM.

FORM GET_PLANT_NAME.
     SELECT * FROM T001W
        WHERE SPRAS = SY-LANGU
        AND WERKS = MARD-WERKS.
     ENDSELECT.
ENDFORM.

FORM GET_STORAGE_NAME.
     SELECT * FROM T001L
        WHERE WERKS = MARD-WERKS
        AND LGORT = MARD-LGORT.
     ENDSELECT.
ENDFORM.

FORM BUILD-RECORD.
     MOVE MARD-WERKS TO RECORD-PLANT.
     MOVE T001W-NAME1 TO RECORD-PLANTNME.
     MOVE MARD-LGORT TO RECORD-STORE.
     MOVE T001L-LGOBE TO RECORD-STORENME.
     IF MARD-MATNR CO ' 0123456789'.
        MOVE '                  ' TO MATID.
        MATID+12(6) = MARD-MATNR+12(6).
        MOVE MATID TO RECORD-MATNR.
     ELSE.
        MOVE MARD-MATNR TO RECORD-MATNR.
     ENDIF.
     MOVE MARD-LABST TO RECORD-QUANTITY.
     MOVE T006A-MSEH6 TO RECORD-UNIT.
     MOVE MARD-LGPBE TO RECORD-BIN.
ENDFORM.

FORM PRINT_TITLE.
     FORMAT INTENSIFIED OFF.
     WRITE: / TEXT-003, SY-DATUM, 82 TEXT-004, SY-PAGNO.
     WRITE: / SY-UZEIT UNDER SY-DATUM, SY-REPID UNDER TEXT-004.
     WRITE: /19 TEXT-002.
     ULINE.
     FORMAT INTENSIFIED ON.
ENDFORM.
