*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMM_TG_T001WTOP.                  " Global Data
  INCLUDE LZMM_TG_T001WUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMM_TG_T001WF00                        . " subprograms
  INCLUDE LZMM_TG_T001WI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMM_TG_T001WF...                  " Subprograms
* INCLUDE LZMM_TG_T001WO...                  " PBO-Modules
* INCLUDE LZMM_TG_T001WI...                  " PAI-Modules
