REPORT ZMMARK35.
TABLES: TNAD7.

SELECT * FROM TNAD7.
  MOVE 'A001' TO TNAD7-LGORT.
  MOVE TNAD7-WERKS TO TNAD7-DSUF1.
  MOVE 'X' TO TNAD7-DELET.
* INSERT TNAD7.
  WRITE: /001 TNAD7.
ENDSELECT.
SKIP.

SELECT * FROM TNAD7
  WHERE LGORT EQ SPACE.
* DELETE TNAD7.
  WRITE: /001 TNAD7.
ENDSELECT.
SKIP.

SELECT * FROM TNAD7
  WHERE WERKS EQ '0001'.
* DELETE TNAD7.
  WRITE: /001 TNAD7.
ENDSELECT.
