*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMMS2CTOP.                        " Global Data
  INCLUDE LZMMS2CUXX.                        " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMMS2CF00                              . " subprograms
  INCLUDE LZMMS2CI00                              . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMMS2CF...                        " Subprograms
* INCLUDE LZMMS2CO...                        " PBO-Modules
* INCLUDE LZMMS2CI...                        " PAI-Modules

INCLUDE LZMMS2CO01.

INCLUDE LZMMS2CI01.
